name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        
        Thank you for suggesting a new feature! Your input helps make this project better for everyone.
        
        Please provide detailed information below to help us understand and evaluate your request.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see added? Please be as specific as possible and include any relevant examples, libraries, or implementations you've seen elsewhere.
      placeholder: "Describe the feature in detail..."
    validations:
      required: true
  - type: textarea
    id: value-add
    attributes:
      label: Why This Feature Matters
      description: Help us understand the value this feature would bring. How would it improve the project? What problems would it solve?
      placeholder: "Explain the benefits and use cases..."
    validations:
      required: false