name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thank you for reporting a bug! Your help in identifying issues makes this project more stable and reliable.

        Please fill out the information below so we can reproduce and fix the issue quickly.
  - type: textarea
    id: what-happened
    attributes:
      label: What Went Wrong?
      description: Describe the bug you encountered. What did you expect to happen vs. what actually happened?
      placeholder: "Clearly describe the issue, including what you expected vs. what occurred..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Which steps should someone take to run into the same error?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Error Logs & Stack Traces
      description: Paste any relevant error messages, logs, or stack traces here. This helps us pinpoint the exact issue.
      placeholder: "Paste your error logs here..."
      render: shell
