name: General Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        ## ❓ General Question
        
        Have a question about the project? You're in the right place! We're here to help.
        
        Please provide as much context as possible so we can give you the best answer.
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know? Include any relevant context, what you've already tried, or specific use cases you're working with.
      placeholder: "Ask your question here. Feel free to include background information, code snippets, or examples to help us understand what you're looking for..."
    validations:
      required: true