site_name: "bubl-ai"
site_dir: ../site
nav:
  - Home:
    - index.md
    - Hello World: hello_world.md

theme:
  logo: _static/logo.png
  favicon: _static/logo.png
  features:
  - navigation.indexes
  - navigation.instant
  - toc.follow
  - search.suggest
  - search.highlight
  - content.code.copy
  name: material
  palette:
    - accent: indigo
      media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
plugins:
  - search
  - include_dir_to_nav
  - mkdocs-jupyter:
      execute: false