site_name: "bubl-ai"
site_dir: ../site
nav:
  - Home:
    - index.md
    - Hello World: hello_world.md
    - RPi Setup: rpi_setup.md
  - Social:
    - social/index.md
    - LinkedIn: https://linkedin.com/in/santiago-olivar
    - GitHub: https://github.com/bubl-ai/
    - HuggingFace: https://huggingface.co/bubl-ai
    - Email: mailto:contact.bubl.ai@example.com

theme:
  logo: _static/logo.png
  favicon: _static/logo.png
  features:
  - navigation.indexes
  - navigation.instant
  - toc.follow
  - search.suggest
  - search.highlight
  - content.code.copy
  name: material
  palette:
    - accent: green
      media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
plugins:
  - search
  - include_dir_to_nav
  - mkdocs-jupyter:
      execute: false

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/santiago-olivar
    - icon: fontawesome/brands/github
      link: https://github.com/bubl-ai/
    - icon: fontawesome/solid/envelope
      link: mailto:contact.bubl.ai@example.com
    - icon: fontawesome/solid/face-grin-tears
      link: https://huggingface.co/bubl-ai